# Generated by Django 5.0.6 on 2025-10-03 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='matricule',
            field=models.CharField(default=2032232, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
