# Generated by Django 5.0.6 on 2025-10-03 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eleve',
            name='matricule',
        ),
    ]
