# Generated by Django 5.0.6 on 2025-10-04 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0003_remove_eleve_matricule'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='password',
            field=models.CharField(default=12345678, max_length=200),
            preserve_default=False,
        ),
    ]
