# Generated by Django 5.0.6 on 2025-10-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0004_eleve_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='password',
            field=models.CharField(default=12345678, max_length=200),
            preserve_default=False,
        ),
    ]
