# Generated by Django 5.0.6 on 2025-10-06 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0007_alter_evaluation_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classe',
            unique_together={('libelle', 'code')},
        ),
    ]
