# Generated by Django 5.0.6 on 2025-10-06 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0008_alter_classe_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='lieu_naissance',
            field=models.CharField(default='douala', max_length=255),
        ),
        migrations.AddField(
            model_name='eleve',
            name='sexe',
            field=models.CharField(choices=[('Masculin', 'Masculin'), ('Feminin', 'Feminin')], default='Feminin', max_length=50),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='sexe',
            field=models.CharField(choices=[('Masculin', 'Masculin'), ('Feminin', 'Feminin')], default='Feminin', max_length=50),
        ),
    ]
